# -*- coding: utf-8 -*-
"""example_usage

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aaRdEPgZD-iTUU3WZrFMN3Ix9k6h6lvJ
"""

# ==============================================================================
# Example Usage of WithCovariateMDS using Synthetic Data
# ==============================================================================
# This script generates a synthetic dataset and demonstrates how to initialize,
# fit, and visualize the Covariate-Adjusted MDS model.
# ==============================================================================

import pandas as pd
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Set sample size (number of participants)
n_samples = 500

# Generate Dummy Data
data = {
    # Personality trait items: Standard Normal Distribution N(0, 1)
    'item_1':     np.random.normal(0.0, 1.0, n_samples),
    'item_2':     np.random.normal(0.0, 1.0, n_samples),
    'item_3':     np.random.normal(0.0, 1.0, n_samples),
    'item_4':     np.random.normal(0.0, 1.0, n_samples),
    'item_5':     np.random.normal(0.0, 1.0, n_samples),
    'item_6':     np.random.normal(0.0, 1.0, n_samples),

    # Covariate 1: Beta Distribution Beta(2, 5)
    # Values tend to be skewed towards 0 (lower values)
    'covariate1': np.random.beta(2.0, 5.0, n_samples),

    # Covariate 2: Beta Distribution Beta(5, 2)
    # Values tend to be skewed towards 1 (higher values)
    'covariate2': np.random.beta(5.0, 2.0, n_samples),
}

# Convert to DataFrame and round values for cleaner output
df_dummy = pd.DataFrame(data).round(4)

print("\n")
print(df_dummy.head())
print("\n")

# Run MDS Analysis
from WithCovariateMDS import WithCovariateMDS

traits = ['item_1', 'item_2', 'item_3', 'item_4', 'item_5', 'item_6']
covariates = ['covariate1', 'covariate2']

model = WithCovariateMDS(n_dim=2)
model.fit(df_dummy, trait_cols=traits, covariate_cols=covariates)

model.summary()
model.plot_standard()
model.plot_covariate()
model.plot_overlay()
model.plot_overlay_with_arrows()