# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dqCrc1-qOyOMB42x1_nQOo5wSA0u33d
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.spatial.distance import pdist       # Function to compute distances between all pairs
from scipy.stats import norm                    # Normal distribution functions (used for p-values)
from scipy.linalg import orthogonal_procrustes # Function to align two configurations (rotation)
from itertools import combinations              # Function to generate all possible pairs
from scipy.spatial.distance import squareform

# ==============================================================================
# Definition of the WithCovariateMDS Class
# ==============================================================================
class WithCovariateMDS:

    def __init__(self, n_dim=2):
        """
        [Initialization Method] Settings executed when the class is instantiated.
        """
        # --- Basic Settings ---
        self.n_dim = n_dim             # Target dimensionality (usually 2D for human interpretation)
        self.items = None              # List of variables for multidimensional scaling
        self.covariate_names = []      # List of covariate names to investigate

        # --- Storage for Standard MDS results (baseline, no covariates) ---
        self.std_X = None              # Estimated coordinates (N rows x 2 columns matrix)
        self.std_sigma = None          # Sigma (error dispersion) for standard MDS

        # --- Storage for Proposed Method results (MDS adjusted with covariates) ---
        self.cov_X = None              # Coordinates with bias removed via covariates
        self.cov_betas = {}            # Bias coefficients (beta) showing how covariates distort distances
        self.cov_sigma = None          # Sigma (error dispersion) for covariate-adjusted MDS
        self.res_cov = None            # Complete record of the scipy optimization process

    def _nll_complex(self, params, log_delta_obs, v_r_matrix, N, M, A, K):
        """
        [Likelihood Calculation Function]
        Called by the minimize function to calculate the discrepancy between the model and observed data.
        A smaller Negative Log-Likelihood value indicates a better fit to the data.

        Arguments:
        params        : Candidate parameters passed by the optimization algorithm (long 1D array)
        log_delta_obs : Observed log-distances computed from actual responses
        v_r_matrix    : Matrix containing respondents' covariate data
        N             : Number of items/variables being scaled
        M             : Number of respondents (e.g., 500)
        A             : Number of dimensions (e.g., 2)
        K             : Number of covariates (0 if no covariates are used)
        """

        # ---------------------------------------------------------
        # 1. Decompose the flat params array into coordinates and beta coefficients
        # ---------------------------------------------------------

        size_X = N * A  # Number of coordinate parameters (e.g., 6 items x 2D = 12)
        size_beta_one_set = int(N * (N - 1) / 2) # Total number of pairs (e.g., 6C2 = 15 pairs)

        # Extract coordinate parameters and reshape into an N x A matrix
        X = params[:size_X].reshape((N, A))

        # Extract bias coefficients (beta) for each of the K covariates
        betas = []
        if K > 0:
            for k in range(K):
                # Cut blocks of beta for each covariate from the params array
                start_idx = size_X + k * size_beta_one_set
                end_idx = start_idx + size_beta_one_set
                # Reshape into a (1 x n_pairs) horizontal vector for matrix calculation
                betas.append(params[start_idx : end_idx].reshape(1, -1))

        # The final parameter is the log of the error standard deviation (sigma)
        log_sigma = params[-1]
        # Variance must be positive; estimated as log and converted back using exp
        variance = np.exp(log_sigma) ** 2

        # ---------------------------------------------------------
        # 2. Calculate predicted values based on the model
        # ---------------------------------------------------------

        # Calculate Euclidean distances between items from current coordinate candidates
        d_vec = pdist(X)

        # Ensure a minimum value (1e-10) to avoid errors in log calculation if distance is 0
        d_vec = np.maximum(d_vec, 1e-10)

        # Take the log to match the model formula
        ln_d = np.log(d_vec).reshape(1, -1)

        # Calculate the magnitude of bias caused by covariates
        bias_term = np.zeros_like(log_delta_obs) # Initialize a zero matrix of the same shape as observed data
        for k in range(K):
            # Respondent covariates (column vector) x Bias coefficients (row vector)
            # = Bias amount per respondent per pair
            bias_term += v_r_matrix[:, [k]] @ betas[k]

        # ---------------------------------------------------------
        # 3. Calculate the "discrepancy (residuals)" between observed and predicted values
        # ---------------------------------------------------------

        # Residual = Observed distance - (Distance from coordinates + Covariate bias)
        residuals = log_delta_obs - (ln_d + bias_term)

        # Sum of Squared Errors (SSE)
        sse = np.sum(residuals**2)

        # ---------------------------------------------------------
        # 4. Calculate and return the Negative Log-Likelihood (NLL)
        # ---------------------------------------------------------

        # Based on the log-normal model by Ramsay (1977)
        n_total = log_delta_obs.size # Total data points (respondents x pairs)
        nll = (n_total / 2.0) * np.log(2 * np.pi) + n_total * log_sigma + sse / (2.0 * variance)

        return nll # The minimize function adjusts parameters to minimize this value


    def fit(self, df, trait_cols, covariate_cols=None):
        """
        [Model Fitting Method]
        Main function called by the user to execute data preprocessing, standard MDS estimation,
        covariate-adjusted MDS estimation, and Procrustes alignment.
        """

        # ---------------------------------------------------------
        # 1. Basic Setup
        # ---------------------------------------------------------
        self.items = list(trait_cols) # Store item names
        N = len(self.items)           # Number of items
        M = len(df)                   # Number of respondents
        A = self.n_dim                # Dimensionality
        n_pairs = int(N * (N - 1) / 2) # Total number of pairs


        # Fix random seed for reproducibility
        np.random.seed(142)

        # ---------------------------------------------------------
        # 2. Compute observed log-distances from raw data
        # ---------------------------------------------------------

        dist_records = [] # List to store distance data for all respondents

        for idx, row in df.iterrows(): # Loop through each respondent (row)
            # Create all possible pairs (t1, t2)
            # Distance is defined as the absolute difference between scores
            # Add a micro-value 1e-5 to avoid log(0) errors
            dists = [np.abs(row[t1] - row[t2]) + 1e-5 for t1, t2 in combinations(self.items, 2)]

            # Convert calculated distances to log and append to list
            dist_records.append(np.log(dists))

        # Convert list to a numpy array. This is the target observation data (y)
        y = np.array(dist_records)

        # ---------------------------------------------------------
        # 3. Estimate Standard MDS (No Covariates)
        # ---------------------------------------------------------

        v_empty = np.zeros((M, 0)) # Create an empty matrix as there are no covariates

        # Set initial parameter candidates (random coordinates, sigma starts at 0)
        init_params_std = np.concatenate([np.random.normal(0, 0.1, N*A), [0.0]])

        # Execute optimization using the BFGS method
        res_std = minimize(self._nll_complex, init_params_std,
                           args=(y, v_empty, N, M, A, 0), method='BFGS',options={'gtol': 1e-6})

        # Extract coordinates from the resulting parameter array
        raw_std_X = res_std.x[:N*A].reshape(N, A)

        # Center coordinates so the configuration is placed at the origin (0,0)
        self.std_X = raw_std_X - raw_std_X.mean(axis=0)
        self.std_sigma = np.exp(res_std.x[-1]) # Store the estimated error standard deviation

        # ---------------------------------------------------------
        # 4. Estimate Covariate-Adjusted MDS
        # ---------------------------------------------------------

        # Execute only if covariates are specified and not empty
        if covariate_cols is not None and len(covariate_cols) > 0:
            self.covariate_names = list(covariate_cols) # Store covariate names
            K = len(self.covariate_names)               # Number of covariates
            v = df[self.covariate_names].values         # Matrix of covariate data

            # Set initial values using coordinates from Standard MDS (self.std_X)
            # to speed up optimization and avoid local minima.
            init_params_cov = np.concatenate([
                self.std_X.flatten(),     # Coordinates from standard MDS
                np.zeros(n_pairs * K),    # Initialize bias coefficients (beta) at 0
                [res_std.x[-1]]           # Use standard MDS variance as the starting point
            ])

            # Execute optimization (passing covariates 'v' and their count 'K')
            self.res_cov = minimize(self._nll_complex, init_params_cov,
                                    args=(y, v, N, M, A, K), method='BFGS',options={'gtol': 1e-6})

            # Extract estimated coordinates
            raw_cov_X = self.res_cov.x[:N*A].reshape(N, A)

            # ---------------------------------------------------------
            # Perform Procrustes analysis to align configurations
            # ---------------------------------------------------------

            # MDS solutions are invariant to rotation and reflection.
            # Align the covariate-adjusted coordinates to the orientation of the standard MDS
            # configuration to allow for meaningful comparison/overlay.

            X_target = self.std_X - self.std_X.mean(axis=0) # Target orientation (Standard MDS)
            X_source = raw_cov_X - raw_cov_X.mean(axis=0)   # Configuration to rotate (Covariate MDS)

            # Compute the optimal rotation/reflection matrix R
            R, _ = orthogonal_procrustes(X_source, X_target)

            # Store final coordinates after applying the transformation
            self.cov_X = X_source @ R

            # Store error standard deviation
            self.cov_sigma = np.exp(self.res_cov.x[-1])

            # Extract and store bias coefficients (beta) for each covariate
            for k, name in enumerate(self.covariate_names):
                start_idx = N * A + k * n_pairs # Start index of beta in the array
                self.cov_betas[name] = self.res_cov.x[start_idx : start_idx + n_pairs]

        # Return self to allow method chaining (e.g., model.fit().summary())
        return self


    def summary(self):
        """
        [Summary Output Method]
        Calculates whether the estimated bias coefficients (beta) are statistically significant
        (whether they truly have an effect) and computes the 95% Confidence Interval.
        Outputs the results to the console in a table format suitable for academic papers.
        """
        if not self.covariate_names:
            print("Cannot output summary because no covariates were specified.")
            return

        N = len(self.items)
        A = self.n_dim
        n_pairs = int(N * (N - 1) / 2)

        # Calculate the "Standard Error" for each parameter from the optimization result (inverse Hessian matrix)
        # A smaller standard error means higher estimation accuracy
        try:
            se_all = np.sqrt(np.abs(np.diag(self.res_cov.hess_inv)))
        except:
            print("Failed to calculate standard error (optimization might not have fully converged).")
            return

        # Output table header (expanding width to 130 to accommodate 95% CI)
        print("\n" + "="*130)
        # Keep Pair width <45, and add 95% CI column
        print(f"{'Covariate':<15} {'Pair':<45} {'Est.':>8} {'Std.Err':>8} {'95% CI':>18} {'z-val':>8} {'p-val':>8}   {'Sig.'}")
        print("-" * 130)

        # Create a list of all possible pair names
        pair_labels = [f"{self.items[i]} - {self.items[j]}" for i, j in combinations(range(N), 2)]

        # z-value used for 95% Confidence Interval calculation (two-tailed 95%, so upper 2.5% point ≈ 1.95996)
        z_crit = norm.ppf(0.975)

        # Output results sequentially for each covariate and each pair
        for k, name in enumerate(self.covariate_names):
            for p_idx, p_label in enumerate(pair_labels):

                idx = (N * A) + (k * n_pairs) + p_idx
                est = self.res_cov.x[idx]
                se = se_all[idx]
                z = est / (se + 1e-10)
                p = 2 * (1 - norm.cdf(np.abs(z)))

                # Calculate lower and upper limits of 95% Confidence Interval
                ci_lower = est - z_crit * se
                ci_upper = est + z_crit * se
                # Format into readable brackets "[lower, upper]"
                ci_str = f"[{ci_lower:.3f}, {ci_upper:.3f}]"

                # Add standard asterisk marks for papers according to how small the p-value is
                sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else "†" if p < 0.1 else ""

                # Output row by row aligning decimal places (Keep p_label width <45, add 95% CI)
                print(f"{name:<15} {p_label:<45} {est:8.3f} {se:8.3f} {ci_str:>18} {z:8.2f} {p:8.4f}   {sig}")

        print("-" * 130)

        # Display overall model fit (error variance) for comparison
        print(f"Residual Sigma (Standard):  {self.std_sigma:.4f}")
        print(f"Residual Sigma (Covariate): {self.cov_sigma:.4f}")
        print("="*130)

        # ---------------------------------------------------------
        # 5. Output distance matrices between items and their differences
        # ---------------------------------------------------------
        print("\n" + "="*130)
        print("DISTANCE MATRIX COMPARISON (Structural Changes)")
        print("="*130)

        # 1. Calculate Euclidean distance matrix between all items from standard MDS coordinates
        dist_std = squareform(pdist(self.std_X))

        # 2. Calculate Euclidean distance matrix between all items from covariate-adjusted coordinates
        dist_cov = squareform(pdist(self.cov_X))

        # 3. Calculate the difference matrix (Adjusted - Standard)
        # Positive value: Pair was actually "more distant" after removing covariate (bias)
        # Negative value: Pair was actually "closer" after removing covariate (bias)
        dist_diff = dist_cov - dist_std

        # Format and output as Pandas DataFrame for readability
        print("\n[A] Standard MDS Distance Matrix (Observed Structure)")
        print(pd.DataFrame(dist_std, index=self.items, columns=self.items).round(3))

        print("\n[B] Covariate-Adjusted Distance Matrix (Bias-Removed Structure)")
        print(pd.DataFrame(dist_cov, index=self.items, columns=self.items).round(3))

        print("\n[C] Difference Matrix (Adjusted - Standard)")
        print("Interpretation:")
        print("  Positive (+): These items are actually MORE DISTANT than they appear in standard MDS.")
        print("  Negative (-): These items are actually CLOSER than they appear in standard MDS.\n")
        print(pd.DataFrame(dist_diff, index=self.items, columns=self.items).round(3))

        print("="*130)

        # ---------------------------------------------------------
        # 6. Distance Matrix Comparison
        # ---------------------------------------------------------
        print("\n" + "="*110)
        print("DISTANCE MATRIX COMPARISON (Structural Changes)")
        print("="*110)

        # 1. Matrix from Standard MDS coordinates
        dist_std = squareform(pdist(self.std_X))

        # 2. Matrix from Covariate-Adjusted coordinates
        dist_cov = squareform(pdist(self.cov_X))

        # 3. Difference matrix (Adjusted - Standard)
        dist_diff = dist_cov - dist_std
        print("\n[A] Standard MDS Distance Matrix (Unadjusted Estimated Structure)")
        print(pd.DataFrame(dist_std, index=self.items, columns=self.items).round(3))

        print("\n[B] Covariate-Adjusted Distance Matrix (Bias-Removed Structure)")
        print(pd.DataFrame(dist_cov, index=self.items, columns=self.items).round(3))

        print("\n[C] Difference Matrix (Adjusted - Standard)")
        print("Interpretation:")
        print("  Positive (+): These items are actually MORE DISTANT than they appear in standard MDS.")
        print("  Negative (-): These items are actually CLOSER than they appear in standard MDS.\n")
        print(pd.DataFrame(dist_diff, index=self.items, columns=self.items).round(3))

        print("="*110)
        print("\n" * 3)


    def plot_standard(self):
        """
        [Plot Method 1] Plots coordinates for standard MDS (baseline).
        """
        if self.std_X is None: raise ValueError("Execute fit() before plotting.")

        plt.figure(figsize=(8, 8))

        # Draw origin cross-lines
        plt.axhline(0, color='gray', lw=0.5, ls='--')
        plt.axvline(0, color='gray', lw=0.5, ls='--')

        # Scatter plot for standard MDS (gray points)
        plt.scatter(self.std_X[:, 0], self.std_X[:, 1], c='gray', s=80, zorder=3, edgecolors='white', linewidth=1.5)

        # Item labels
        for i, txt in enumerate(self.items):
            plt.annotate(txt, (self.std_X[i, 0], self.std_X[i, 1]),
                         xytext=(8, 8), textcoords='offset points', size=10, zorder=4)

        ax = plt.gca()
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.title("Standard ML-MDS (no covariate)", fontsize=14, weight='bold', y=1.05)
        ax.set_aspect('equal', adjustable='box')

        max_coord = np.max(np.abs(self.std_X))
        plt.xlim(-max_coord*1.3, max_coord*1.3)
        plt.ylim(-max_coord*1.3, max_coord*1.3)

        plt.show()
        print("\n" * 3)
        plt.close()


    def plot_covariate(self):
        """
        [Plot Method 2] Plots covariate-adjusted MDS coordinates.
        """
        if self.cov_X is None: raise ValueError("Covariate MDS has not been estimated.")

        plt.figure(figsize=(8, 8))
        plt.axhline(0, color='gray', lw=0.5, ls='--')
        plt.axvline(0, color='gray', lw=0.5, ls='--')

        # Adjusted points (blue)
        plt.scatter(self.cov_X[:, 0], self.cov_X[:, 1], c='royalblue', s=80, zorder=3, edgecolors='white', linewidth=1.5)

        for i, txt in enumerate(self.items):
            plt.annotate(txt, (self.cov_X[i, 0], self.cov_X[i, 1]),
                         xytext=(8, 8), textcoords='offset points', size=10, zorder=4)

        ax = plt.gca()
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.title("Covariate-Adjusted MDS", fontsize=14, weight='bold', y=1.05)
        ax.set_aspect('equal', adjustable='box')

        max_coord = np.max(np.abs(self.cov_X))
        plt.xlim(-max_coord*1.3, max_coord*1.3)
        plt.ylim(-max_coord*1.3, max_coord*1.3)

        plt.show()
        print("\n" * 3)
        plt.close()


    def plot_overlay(self):
        """
        [Plot Method 3] Overlays standard MDS and covariate MDS configurations.
        """
        if self.cov_X is None or self.std_X is None:
            raise ValueError("Both models must be estimated.")

        plt.figure(figsize=(9, 9))
        plt.axhline(0, color='lightgray', lw=0.5, ls='--')
        plt.axvline(0, color='lightgray', lw=0.5, ls='--')

        # 1. Standard MDS points (Gray dashed hollow circles)
        plt.scatter(self.std_X[:, 0], self.std_X[:, 1], facecolors='none', edgecolors='gray',
                    s=100, zorder=2, linestyles='dashed', label='Standard MDS')

        # 2. Covariate MDS points (Blue solid circles)
        plt.scatter(self.cov_X[:, 0], self.cov_X[:, 1], c='royalblue',
                    s=100, zorder=3, edgecolors='white', label='Covariate MDS')

        for i in range(len(self.items)):
            plt.annotate(self.items[i], (self.cov_X[i, 0], self.cov_X[i, 1]),
                         xytext=(10, 10), textcoords='offset points', size=10,zorder=4)

        ax = plt.gca()
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.title("Configuration Shift: Standard vs. Covariate-Adjusted", fontsize=15, y=1.05)
        plt.legend(loc='upper right', frameon=False)
        ax.set_aspect('equal', adjustable='box')

        max_coord = max(np.max(np.abs(self.std_X)), np.max(np.abs(self.cov_X)))
        plt.xlim(-max_coord*1.3, max_coord*1.3)
        plt.ylim(-max_coord*1.3, max_coord*1.3)

        plt.show()
        print("\n" * 3)
        plt.close()

    def plot_overlay_with_arrows(self):
        """
        [Plot Method 4] Overlays configurations with arrows indicating movement.
        Labels are placed automatically beyond the arrow direction.
        """
        if self.cov_X is None or self.std_X is None:
            raise ValueError("Both models must be estimated.")

        plt.figure(figsize=(9, 9))
        plt.axhline(0, color='lightgray', lw=0.5, ls='--')
        plt.axvline(0, color='lightgray', lw=0.5, ls='--')

        plt.scatter(self.std_X[:, 0], self.std_X[:, 1], facecolors='none', edgecolors='gray',
                    s=100, zorder=2, linestyles='dashed', label='Standard MDS')

        plt.scatter(self.cov_X[:, 0], self.cov_X[:, 1], c='royalblue',
                    s=100, zorder=3, edgecolors='white', label='Covariate MDS')

        max_coord = max(np.max(np.abs(self.std_X)), np.max(np.abs(self.cov_X)))
        offset_dist = max_coord * 0.08

        for i in range(len(self.items)):
            # Draw arrows
            plt.annotate('',
                         xy=(self.cov_X[i, 0], self.cov_X[i, 1]),
                         xytext=(self.std_X[i, 0], self.std_X[i, 1]),
                         arrowprops=dict(arrowstyle='->', color='gray', lw=1.5, alpha=0.7,
                                         shrinkA=8, shrinkB=8),
                         zorder=1)

            # Text positioning on the extension of the vector
            dx = self.cov_X[i, 0] - self.std_X[i, 0]
            dy = self.cov_X[i, 1] - self.std_X[i, 1]
            length = np.hypot(dx, dy)

            if length > 1e-5:
                text_x = self.cov_X[i, 0] + (dx / length) * offset_dist
                text_y = self.cov_X[i, 1] + (dy / length) * offset_dist
            else:
                orig_len = np.hypot(self.cov_X[i, 0], self.cov_X[i, 1])
                text_x = self.cov_X[i, 0] + (self.cov_X[i, 0] / (orig_len + 1e-10)) * offset_dist
                text_y = self.cov_X[i, 1] + (self.cov_X[i, 1] / (orig_len + 1e-10)) * offset_dist

            plt.text(text_x, text_y, self.items[i],
                     ha='center', va='center', size=10, zorder=4)

        ax = plt.gca()
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.title("Configuration Shift (with Arrows)", fontsize=15, y=1.05)
        plt.legend(loc='upper right', frameon=False)
        ax.set_aspect('equal', adjustable='box')

        plt.xlim(-max_coord*1.35, max_coord*1.35)
        plt.ylim(-max_coord*1.35, max_coord*1.35)

        plt.show()
        print("\n" * 3)
        plt.close()

    def plot_overlay_arrows_no_text(self):
        """
        [Plot Method 5] Overlays configurations with arrows but without labels.
        """
        if self.cov_X is None or self.std_X is None:
            raise ValueError("Both models must be estimated.")

        plt.figure(figsize=(9, 9))
        plt.axhline(0, color='lightgray', lw=0.5, ls='--')
        plt.axvline(0, color='lightgray', lw=0.5, ls='--')

        plt.scatter(self.std_X[:, 0], self.std_X[:, 1], facecolors='none', edgecolors='gray',
                    s=100, zorder=2, linestyles='dashed', label='Standard MDS')

        plt.scatter(self.cov_X[:, 0], self.cov_X[:, 1], c='royalblue',
                    s=100, zorder=3, edgecolors='white', linewidth=1.5, label='Covariate MDS')

        for i in range(len(self.items)):
            plt.annotate('',
                         xy=(self.cov_X[i, 0], self.cov_X[i, 1]),
                         xytext=(self.std_X[i, 0], self.std_X[i, 1]),
                         arrowprops=dict(arrowstyle='->', color='gray', lw=1.5, alpha=0.7,
                                         shrinkA=8, shrinkB=8),
                         zorder=1)

        ax = plt.gca()
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.title("Configuration Shift (Arrows only, No Text)", fontsize=15, y=1.05)
        plt.legend(loc='upper right', frameon=False)
        ax.set_aspect('equal', adjustable='box')

        max_coord = max(np.max(np.abs(self.std_X)), np.max(np.abs(self.cov_X)))
        plt.xlim(-max_coord*1.35, max_coord*1.35)
        plt.ylim(-max_coord*1.35, max_coord*1.35)

        plt.show()
        print("\n" * 3)
        plt.close()

    def plot_overlay_no_text_no_arrow(self):
        """
        [Plot Method 6] Overlays configurations without arrows and labels.
        """
        if self.cov_X is None or self.std_X is None:
            raise ValueError("Both models must be estimated.")

        plt.figure(figsize=(9, 9))
        plt.axhline(0, color='lightgray', lw=0.5, ls='--')
        plt.axvline(0, color='lightgray', lw=0.5, ls='--')

        plt.scatter(self.std_X[:, 0], self.std_X[:, 1], facecolors='none', edgecolors='gray',
                    s=100, zorder=2, linestyles='dashed', label='Standard MDS')

        plt.scatter(self.cov_X[:, 0], self.cov_X[:, 1], c='royalblue',
                    s=100, zorder=3, edgecolors='white', label='Covariate MDS')

        ax = plt.gca()
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.title("Configuration Shift (No Arrows, No Text)", fontsize=15, y=1.05)
        plt.legend(loc='upper right', frameon=False)
        ax.set_aspect('equal', adjustable='box')

        max_coord = max(np.max(np.abs(self.std_X)), np.max(np.abs(self.cov_X)))
        plt.xlim(-max_coord*1.35, max_coord*1.35)
        plt.ylim(-max_coord*1.35, max_coord*1.35)

        plt.show()
        print("\n" * 3)
        plt.close()

    def plot_standard_no_text(self):
        """
        [Plot Method] Standard MDS coordinates (baseline) without labels.
        """
        if self.std_X is None: raise ValueError("Execute fit() before plotting.")

        plt.figure(figsize=(8, 8))
        plt.axhline(0, color='gray', lw=0.5, ls='--')
        plt.axvline(0, color='gray', lw=0.5, ls='--')

        plt.scatter(self.std_X[:, 0], self.std_X[:, 1], c='gray', s=80, zorder=3, edgecolors='white', linewidth=1.5)

        ax = plt.gca()
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.title("Standard ML-MDS without covariate (No Text)", fontsize=14, weight='bold', y=1.05)
        ax.set_aspect('equal', adjustable='box')

        max_coord = np.max(np.abs(self.std_X))
        plt.xlim(-max_coord*1.3, max_coord*1.3)
        plt.ylim(-max_coord*1.3, max_coord*1.3)

        plt.show()
        print("\n" * 3)
        plt.close()

    def plot_covariate_no_text(self):
        """
        [Plot Method] Covariate MDS coordinates without labels.
        """
        if self.cov_X is None: raise ValueError("Covariate MDS has not been estimated.")

        plt.figure(figsize=(8, 8))
        plt.axhline(0, color='gray', lw=0.5, ls='--')
        plt.axvline(0, color='gray', lw=0.5, ls='--')

        plt.scatter(self.cov_X[:, 0], self.cov_X[:, 1], c='royalblue', s=80, zorder=3, edgecolors='white', linewidth=1.5)

        ax = plt.gca()
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.title("Covariate-Adjusted MDS (No Text)", fontsize=14, weight='bold', y=1.05)
        ax.set_aspect('equal', adjustable='box')

        max_coord = np.max(np.abs(self.cov_X))
        plt.xlim(-max_coord*1.3, max_coord*1.3)
        plt.ylim(-max_coord*1.3, max_coord*1.3)

        plt.show()
        print("\n" * 3)
        plt.close()